on:
  push:
    branches: ["main"]

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno install
      - run: deno task check
      - run: deno task build
      - id: id-build-directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: check-and-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: id-build-directory
        uses: actions/deploy-pages@v4
